### ISSUE TITLE
USER STORY: Users able to see events attending and events attended in one place

### ISSUE THREAD

**Issue by Libbu** [Libbu/ci-capstone-project#18]
As a **user** I can **see a consolidated list of events I've said I will attend and those I have attended** so that **I can keep track of my activity**

### Acceptance Criteria:
- Acceptance Criteria 1: Users have an 'attendance' section of the website where they can see what events they have been in and will do.
* Acceptance Criteria 2: User attendance section is clearly divided into past and future.
*  Acceptance Criteria 3: User attendance section updates dynamically with passage of time and user decision.

### Tasks
- [ ] Task 1: Create template and view logic for users to see events they have and will attend.
- [ ] Task 2: Create template logic to intuitively structure the page.
- [ ] Task 3: Connect attendance page to other website areas and ensure consistency of look/feel.
