### ISSUE TITLE
USER STORY: User Consolidated list of Organised Events

### ISSUE THREAD

**Issue by Libbu** [Libbu/ci-capstone-project#19]
As a **site user** I can **see a consolidated list of events I've organised* so that **I can keep track of my plans*

### Acceptance Criteria:
- Acceptance Criteria 1: Section of the website available with User Events present.
* Acceptance Criteria 2: Page lists events user has created.
+ Acceptance Criteria 3: Page is divided between past and future events to avoid cluttering.

### Tasks
- [ ] Task 1: Create template and view logic to provide users with a site that lists their created events.
- [ ] Task 2: User Events page template divides events into past and future categories
- [ ] Task 3: User Events page is connected to the rest of the website and has consistent look and feel.
