### ISSUE TITLE
USER STORY: Site User: Comment on Events

### ISSUE THREAD

**Issue by Libbu** [Libbu/ci-capstone-project#8]
As a **logged-in site user** I can **write comments on events** so that I can **engage with the community**

### Acceptance Criteria:
- Acceptance Criteria 1: Site users/visitors who are not logged-in cannot leave comments.
* Acceptance Criteria 2: Logged in users can leave comments on event posts. 
+ Acceptance Criteria 3: Logged in users can see other comments on the same post. 

### Tasks
- [x] Task 1: develop front-end support for comment functionality in form, html elements, js event listeners.
- [x] Task 2: add comment model
- [x] Task 3: write view logic to support comment submission through relevant event_detail page.
- [x] Task 4: enable editing and deleting of users own comments
